# Generated by Django 5.0.4 on 2024-04-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plate_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
