# Generated by Django 5.0.4 on 2024-04-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingrequest',
            old_name='status',
            new_name='status_request',
        ),
    ]
